### ISSUE TITLE
Feature request: Allow cancelling transactions

### ISSUE THREAD

**Issue by Thegaram** [ObsidianLabs/ConfluxStudio#29]
When I accidentally tried deploying to Oceanus from a local testing account (with zero balance), the transaction seemed to get stuck:

![image](https://user-images.githubusercontent.com/7571518/93209365-53045200-f75e-11ea-9d50-b9e4ff372239.png)

It would be nice if:
- Such transactions could be cancelled by clicking on an `x` on the notification. By cancel, I mean that the UI forgets them.
- There would be a way to get the hash of such transactions so that one can investigate why it's stuck on Conflux Scan.

**Comment by qftgtr** [comment]
Sometimes the Oceanus network gets very slow which is why the deploying notification get stuck.

We implemented a transaction queue in [v0.4.0](https://github.com/ObsidianLabs/ConfluxStudio/releases/tag/v0.4.0). You can send multiple transactions and the queue will manage them without the notification windows bothering you. You can also see their status (mined, executed, or confirmed) and check details (including hash and many others) for both pending and finished transactions.
